# Build Specification Reference for CodeBuild: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  install:
    runtime-versions:
      ruby: latest
  build:
    commands:
      - bin/build.sh ubuntu
      - bin/push.sh ubuntu
      - docker tag $DOCKER_ORG/terraspace:ubuntu $DOCKER_ORG/terraspace:latest
      - docker push $DOCKER_ORG/terraspace:latest
