# Build Specification Reference for CodeBuild: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  install:
    runtime-versions:
      ruby: latest
    commands:
      - bin/install/awscli.sh
  build:
    commands:
      - bin/build.sh $OS
      - bin/push.sh $OS
      - bin/push-latest.sh $OS
